services:
  - type: web
    name: dreamweave
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: FLASK_SECRET_KEY
        sync: false
      - key: X_AI_API_KEY
        sync: false
      - key: X_AI_API_URL
        sync: false 